"""add_patients_and_cases

Revision ID: 6a563b58a60d
Revises: f5ca355bad75
Create Date: 2026-06-04 19:17:10.059891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a563b58a60d'
down_revision: Union[str, Sequence[str], None] = 'f5ca355bad75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pg_trgm extension for GIN trigram fuzzy search
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('address', sa.String(length=1000), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('navigator_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['navigator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_patients_full_name_trgm', 'patients', ['full_name'], unique=False, postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.create_index('idx_patients_navigator', 'patients', ['navigator_id'], unique=False)
    op.create_index('idx_patients_status', 'patients', ['status'], unique=False)
    op.create_table('cases',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis', sa.String(length=5000), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='new', nullable=False),
    sa.Column('priority', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recommended_hospital_id', sa.UUID(), nullable=True),
    sa.Column('applied_funding_id', sa.UUID(), nullable=True),
    sa.Column('assigned_clinician_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_clinician_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cases_created_by', 'cases', ['created_by'], unique=False)
    op.create_index('idx_cases_patient', 'cases', ['patient_id'], unique=False)
    op.create_index('idx_cases_priority', 'cases', ['priority'], unique=False)
    op.create_index('idx_cases_status', 'cases', ['status'], unique=False)
    op.create_index('idx_cases_status_priority', 'cases', ['status', 'priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cases_status_priority', table_name='cases')
    op.drop_index('idx_cases_status', table_name='cases')
    op.drop_index('idx_cases_priority', table_name='cases')
    op.drop_index('idx_cases_patient', table_name='cases')
    op.drop_index('idx_cases_created_by', table_name='cases')
    op.drop_table('cases')
    op.drop_index('idx_patients_status', table_name='patients')
    op.drop_index('idx_patients_navigator', table_name='patients')
    op.drop_index('idx_patients_full_name_trgm', table_name='patients', postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.drop_table('patients')
    # ### end Alembic commands ###
