"""add_clinician_reviews

Revision ID: 8a69c2c6df35
Revises: b2c3d4e5f6a7
Create Date: 2026-06-05 12:24:34.838763

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8a69c2c6df35'
down_revision: str | Sequence[str] | None = 'b2c3d4e5f6a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_timeline_event_type'), table_name='timeline_events')
    op.create_index(op.f('ix_timeline_events_event_type'), 'timeline_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_events_event_type'), table_name='timeline_events')
    op.create_index(op.f('idx_timeline_event_type'), 'timeline_events', ['event_type'], unique=False)
    # ### end Alembic commands ###
