"""add_follow_ups

Revision ID: 9933d56e8bcc
Revises: 8a69c2c6df35
Create Date: 2026-06-05 12:40:16.971670

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '9933d56e8bcc'
down_revision: str | Sequence[str] | None = '8a69c2c6df35'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
