"""add_hospitals

Revision ID: c8921a6eee2f
Revises: caf220bea201
Create Date: 2026-06-05 12:55:43.078692

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c8921a6eee2f'
down_revision: str | Sequence[str] | None = 'caf220bea201'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_funding_programs_name'), table_name='funding_programs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_funding_programs_name'), 'funding_programs', ['name'], unique=False)
    # ### end Alembic commands ###
