"""add_funding_programs

Revision ID: caf220bea201
Revises: 9933d56e8bcc
Create Date: 2026-06-05 12:41:22.157827

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'caf220bea201'
down_revision: str | Sequence[str] | None = '9933d56e8bcc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_programs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('program_type', sa.String(length=50), nullable=True),
    sa.Column('eligibility_criteria', sa.Text(), nullable=True),
    sa.Column('max_amount', sa.Float(), nullable=True),
    sa.Column('min_amount', sa.Float(), nullable=True),
    sa.Column('application_url', sa.String(length=500), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('contact_email', sa.String(length=254), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_funding_programs_is_active', 'funding_programs', ['is_active'], unique=False)
    op.create_index('idx_funding_programs_name', 'funding_programs', ['name'], unique=False)
    op.create_index(op.f('ix_funding_programs_name'), 'funding_programs', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_funding_programs_name'), table_name='funding_programs')
    op.drop_index('idx_funding_programs_name', table_name='funding_programs')
    op.drop_index('idx_funding_programs_is_active', table_name='funding_programs')
    op.drop_table('funding_programs')
    # ### end Alembic commands ###
